# Generated by Django 3.0.5 on 2020-09-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='image',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='accounts',
            name='college_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='degree',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='passout_year',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='school_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='user_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='age',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
