# Generated by Django 3.0.5 on 2020-09-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200920_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='degree',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
