# Generated by Django 3.0.5 on 2020-09-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_accounts_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='degree',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
