# Generated by Django 3.0.5 on 2020-09-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200920_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='college_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='degree',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='passout_year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='school_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
